Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2024-02, with the labels that each got.

#764 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: size/XS

#765 feat: add support for create, update and createOrUpdate in spanner Accessor
  accessors/clients/spanner/admin/interface.go
  accessors/clients/spanner/admin/mocks.go
  accessors/spanner/spanner_accessor.go
  accessors/spanner/spanner_accessor_test.go
  cmd/utils.go
  conversion/conversion.go
  conversion/validations.go
  testing/accessors/spanner/spanner_accessor_test.go
  testing/conversion/conversion_test.go
Labels: size/XXL

#763 chore: Refactor web.go into 3 files
  webv2/api/common.go
  webv2/api/rules.go
  webv2/api/rules_test.go
  webv2/api/schema.go
  webv2/api/schema_test.go
  webv2/config.json
  webv2/routes.go
  webv2/types/types.go
  webv2/web.go
  webv2/web_startup_test.go
Labels: size/XXL

#769 Revert GCP details
  webv2/config.json
Labels: size/XS

#758 ability to pass custom parameters to custom sharding logic
  docs/reverse-replication/ReverseReplicationUserGuide.md
  docs/reverse-replication/RunnigReverseReplication.md
  reverse_replication/reverse-replication-runner.go
Labels: size/M

#770 Refactor reports API and add unit tests
  cmd/data.go
  cmd/schema.go
  cmd/schema_and_data.go
  conversion/conversion.go
  conversion/store_files.go
  internal/reports/report_helpers.go
  internal/reports/report_text.go
  internal/reports/report_v2.go
  internal/reports/types.go
  sources/mysql/report_test.go
  sources/postgres/report_test.go
  webv2/api/reports.go
  webv2/api/reports_test.go
  webv2/api/rules_test.go
  webv2/routes.go
  webv2/web.go
Labels: size/XL

#773 Adding accessor/client for datastream and operations
  accessors/clients/datastream/datastream_client.go
  accessors/clients/datastream/datastream_client_test.go
  accessors/clients/datastream/datastream_test/mocks.go
  accessors/clients/datastream/interface.go
  accessors/clients/operation/operation.go
  accessors/clients/operation/operation_test/mock_operation.go
  accessors/clients/operation/operation_test/operation_test.go
  go.mod
  go.sum
Labels: size/L

#774 feat: accessors required for resource generation
  accessors/clients/datastream/interface.go
  accessors/clients/datastream/mocks.go
  accessors/clients/operation/mock_operation.go
  accessors/clients/operation/operation.go
  accessors/clients/operation/operation_test/operation_test.go
  accessors/clients/storage/interface.go
  accessors/clients/storage/mocks.go
  accessors/datastream/datastream_accessor.go
  accessors/datastream/datastream_accessor_test.go
  accessors/datastream/mocks.go
  accessors/spanner/mocks.go
  accessors/storage/mocks.go
  accessors/storage/storage_accessor.go
  accessors/storage/storage_accessor_test.go
Labels: size/XL

#766 [feat] RR Create API 3: Add DAO to access metadatatables
  dao/dao.go
  dao/dao_client.go
  dao/dao_client_test.go
  webv2/helpers/helpers.go
Labels: size/L
