Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2024-11, with the labels that each got.

#938 refactor: Refactoring utils and common code
  accessors/spanner/spanner_accessor.go
  cmd/utils.go
  common/parse/parse.go
  common/task/task.go
  common/task/task_test.go
  common/utils/utils.go
  conversion/conversion.go
  conversion/data_from_database.go
  conversion/mocks.go
  conversion/resource_generation.go
  conversion/resource_generation_test.go
  sources/common/infoschema.go
  sources/common/mocks.go
  sources/common/utils.go
  sources/common/utils_test.go
Labels: size/XL

#936 feat: Refactor SpannerAccessor and add new APIs
  accessors/clients/spanner/admin/interface.go
  accessors/clients/spanner/admin/mocks.go
  accessors/clients/spanner/client/interface.go
  accessors/clients/spanner/client/mocks.go
  accessors/spanner/mocks.go
  accessors/spanner/spanner_accessor.go
  accessors/spanner/spanner_accessor_test.go
  cmd/data.go
  cmd/utils.go
  conversion/data_from_database.go
  conversion/resource_generation.go
  conversion/resource_generation_test.go
  internal/convert.go
  testing/accessors/spanner/spanner_accessor_test.go
  testing/conversion/conversion_test.go
  webv2/helpers/helpers.go
  webv2/routes.go
  webv2/session/session_service.go
Labels: size/XL

#943 Documentation for Interleave any table
  docs/ui/schema-conv/spanner-draft.md
Labels: size/S

#941 Adding session file as input to schema subcommand and Updating schema subcommand documentation
  cmd/schema.go
  docs/cli/data.md
  docs/cli/schema-and-data.md
  docs/cli/schema.md
Labels: size/M

#937 feat: Add VerifyExpressions API
  accessors/clients/spanner/client/interface.go
  accessors/clients/spanner/client/mocks.go
  cmd/utils.go
  common/constants/constants.go
  conversion/data_from_database.go
  expressions_api/expression_verify.go
  expressions_api/expression_verify_test.go
  internal/convert.go
  test_data/session_expression_verify.json
Labels: size/XL

#942 Add Integration test for VerifyExpressions API
  testing/expressions_api/integration_test.go
Labels: size/L

#946 Fixing broken link in docs
  docs/cli/data.md
  docs/cli/schema-and-data.md
Labels: size/S
