Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2024-07, with the labels that each got.

#853 writer version bump
  reverse_replication/reverse-replication-runner.go
Labels: size/XS

#856 Downgrade CodeCov
  .github/workflows/test-coverage.yaml
Labels: size/XS

#854 MySQL foreign key action handling at the backend with warning generation
  common/constants/constants.go
  internal/convert.go
  internal/mapping.go
  internal/mapping_test.go
  internal/reports/report_helpers.go
  internal/test_util.go
  sources/common/infoschema.go
  sources/common/toddl.go
  sources/common/toddl_test.go
  sources/common/utils.go
  sources/mysql/infoschema.go
  sources/mysql/infoschema_test.go
  sources/mysql/mysqldump.go
  sources/mysql/mysqldump_test.go
  sources/postgres/toddl_test.go
  spanner/ddl/ast.go
  spanner/ddl/ast_test.go
  webv2/api/schema.go
  webv2/api/schema_test.go
Labels: size/XL

#862 Fixing flaky testing in schema_test.go
  webv2/api/schema.go
Labels: size/XS

#864 feat: upgrade pg_query to v5
  go.mod
  go.sum
  sources/postgres/pgdump.go
  sources/postgres/pgdump_test.go
Labels: size/M

#861 test: Add golden tests to PostgreSQL
  test_data/goldens/postgres/create_table.test
  testing/common/goldens.go
  testing/postgres/golden_test.go
Labels: size/L

#866 fix: fix postgresql golden tests
  test_data/goldens/postgres/create_table.test
  testing/common/goldens.go
Labels: size/S

#865 Foreign key actions - warnings for unsupported sources (oracle,etc) and tests for reports
  common/constants/constants.go
  internal/convert.go
  internal/helpers.go
  internal/mapping.go
  internal/mapping_test.go
  internal/reports/report_helpers.go
  sources/common/toddl_test.go
  sources/mysql/infoschema_test.go
  sources/mysql/mysqldump.go
  sources/mysql/mysqldump_test.go
  sources/mysql/report_test.go
  sources/oracle/toddl_test.go
  sources/postgres/infoschema_test.go
  sources/postgres/pgdump.go
  sources/postgres/pgdump_test.go
  sources/postgres/report_test.go
  sources/postgres/toddl_test.go
  sources/sqlserver/toddl_test.go
  spanner/ddl/ast_test.go
  test_data/mysql_structured_report.json
  test_data/mysql_text_report.txt
  test_data/postgres_structured_report.json
  test_data/postgres_text_report.txt
  webv2/api/schema_test.go
Labels: size/XXL

#870 refactor: Refactor golden tests
  test_data/goldens/postgres/create_table.test
  testing/common/goldens.go
  testing/postgres/golden_test.go
Labels: size/L

#867 Making GenerateIdSuffix thread safe
  internal/helpers.go
  internal/helpers_test.go
Labels: size/M

#874 Integration test for Foreign Key Action Migration Feature
  .github/workflows/integration-tests-against-emulator.yaml
  test_data/mysql_foreignkeyaction_dump.test.out
  test_data/pg_dump.test.out
  testing/mysql/integration_test.go
  testing/postgres/integration_test.go
Labels: size/L

#884 fix: add npm-build to Makefile
  .github/workflows/integration-tests-against-emulator.yaml
  Makefile
Labels: size/XS

#872 Support FLOAT32 type in Spanner Migration Tool.
  docs/data-types/mysql.md
  docs/data-types/oracle.md
  docs/data-types/postgres.md
  docs/data-types/sqlserver.md
  sources/common/utils.go
  sources/csv/data.go
  sources/csv/data_test.go
  sources/csv/toddl.go
  sources/csv/toddl_test.go
  sources/mysql/data.go
  sources/mysql/mysqldump_test.go
  sources/mysql/report_test.go
  sources/mysql/toddl.go
  sources/mysql/toddl_test.go
  sources/oracle/data.go
  sources/oracle/data_test.go
  sources/oracle/infoschema_test.go
  sources/oracle/toddl.go
  sources/oracle/toddl_test.go
  sources/postgres/data.go
  sources/postgres/data_test.go
  sources/postgres/infoschema.go
  sources/postgres/infoschema_test.go
  sources/postgres/pgdump_test.go
  sources/postgres/toddl.go
  sources/postgres/toddl_test.go
  sources/spanner/infoschema_test.go
  sources/spanner/toddl.go
  sources/spanner/toddl_test.go
  sources/sqlserver/data.go
  sources/sqlserver/data_test.go
  sources/sqlserver/infoschema_test.go
  sources/sqlserver/toddl.go
  sources/sqlserver/toddl_test.go
  spanner/ddl/ast.go
  spanner/ddl/ast_test.go
  test_data/mysql_structured_report.json
  test_data/mysql_text_report.txt
  webv2/api/rules_test.go
  webv2/api/schema.go
  webv2/api/schema_test.go
Labels: size/XL

#882 Follow up PR on Foreign Keys
  test_data/basic_session_file_test.json
  test_data/basic_sessions_file_wo_sequences_test.json
  test_data/mysql_interleave_session_test.json
  ui/dist/ui/index.html
  ui/dist/ui/main.580952d7b2f83651.js
  ui/dist/ui/main.c8f4d9af2ca45e5b.js
  ui/src/app/model/conv.ts
  ui/src/app/services/conversion/conversion.service.ts
  webv2/api/schema_test.go
Labels: size/M

#881 feature: translate numeric primary keys to text in PostgreSQL
  internal/convert.go
  internal/reports/report_helpers.go
  sources/common/toddl.go
  sources/common/utils.go
  sources/dynamodb/toddl.go
  sources/dynamodb/toddl_test.go
  sources/mysql/toddl.go
  sources/oracle/toddl.go
  sources/postgres/pgdump_test.go
  sources/postgres/toddl.go
  sources/spanner/toddl.go
  sources/spanner/toddl_test.go
  sources/sqlserver/toddl.go
  test_data/pg_dump.test.out
  testing/postgres/integration_test.go
  webv2/api/schema.go
  webv2/utilities/get_type.go
Labels: size/L
