Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2024-05, with the labels that each got.

#818 docs: resource generation and cli dataflow option docs
  docs/cli/config-json.md
  docs/cli/data.md
  docs/cli/schema-and-data.md
  docs/ui/prepare-migration/conn-profiles.md
  docs/ui/ui.md
  test_data/mysql_shard_streaming.cfg
Labels: size/M

#821 Dataflow version bump
  reverse_replication/reverse-replication-runner.go
Labels: size/XS

#823 fixing integration test issue with loading sqlplus
  .github/workflows/integration-tests-against-emulator.yaml
Labels: size/S

#827 Make fastExit false for orchestration and schema
  conversion/data_from_database.go
  sources/common/infoschema.go
Labels: size/XS

#820 feat: create sequence backend
  accessors/spanner/spanner_accessor.go
  common/constants/constants.go
  conversion/store_files.go
  conversion/store_files_test.go
  internal/convert.go
  internal/helpers.go
  sources/mysql/mysqldump_test.go
  sources/postgres/pgdump_test.go
  spanner/ddl/ast.go
  spanner/ddl/ast_test.go
  test_data/basic_session_file_test.json
  test_data/basic_sessions_file_wo_sequences_test.json
  webv2/api/reports.go
  webv2/api/schema.go
  webv2/api/schema_test.go
  webv2/api/sequence.go
  webv2/api/sequence_test.go
  webv2/routes.go
  webv2/table/remove_column.go
  webv2/table/review_table_schema.go
  webv2/table/review_table_schema_test.go
  webv2/table/update_table_schema.go
  webv2/table/update_table_schema_test.go
  webv2/table/utilities.go
Labels: size/XXL
