Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2024-08, with the labels that each got.

#875 Documentation for custom transformation
  docs/index.md
  docs/reverse-replication/ReverseReplicationUserGuide.md
  docs/reverse-replication/RunnigReverseReplication.md
  docs/transformations/CustomTransformation.md
  docs/troubleshoot/minimal.md
  docs/ui/prepare-migration/dataflow-tuning.md
  docs/ui/schema-conv/spanner-draft.md
  reverse_replication/reverse-replication-runner.go
  streaming/streaming.go
Labels: size/L

#883 Default Value Struct changes
  schema/schema.go
  sources/mysql/infoschema.go
  sources/mysql/infoschema_test.go
Labels: size/M

#885 Sanitize Default Value
  sources/mysql/infoschema.go
  sources/mysql/infoschema_test.go
Labels: size/M

#843 fix: deprecate input file pattern
  accessors/dataflow/dataflow_accessor_test.go
  docs/troubleshoot/minimal.md
  streaming/streaming.go
Labels: size/S
