Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2024-06, with the labels that each got.

#831 Update schema.go
  webv2/api/schema.go
  webv2/api/schema_test.go
Labels: size/S

#833 docs: auto-generated keys
  docs/data-types/mysql.md
  docs/ui/schema-conv/issues.md
  docs/ui/schema-conv/schema-conv.md
  docs/ui/schema-conv/spanner-draft.md
Labels: Do not merge, size/M

#847 verify generated files exist in ui/dist
  .github/scripts/verify-files.sh
  .github/workflows/ui-generated-files-check.yaml
  Makefile
Labels: size/M

#848 fix: go mod tidy changes
  go.mod
  go.sum
Labels: size/L
