Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2024-10, with the labels that each got.

#916 Bumping up sqlServer Image to fix issue of permission denied on `/proc/pid/task`
  .github/workflows/integration-tests-against-emulator.yaml
Labels: size/XS

#914 Add Terraform template links in SMT docs
  docs/cli/cli.md
  docs/data-types/schema.md
  docs/limitations.md
  docs/minimal/minimal.md
  docs/monitoring/Monitoring.md
  docs/permissions.md
  docs/poc/poc.md
  docs/reports.md
  docs/reverse-replication/ReverseReplication.md
  docs/terraform.md
  docs/transformations/CustomTransformation.md
  docs/troubleshoot/trouble.md
  docs/ui/ui.md
Labels: size/M

#919 Updating documentation to remove references to Oracle and SQLServer
  docs/cli/flags.md
  docs/data-types/oracle.md
  docs/data-types/schema.md
  docs/data-types/sqlserver.md
  docs/index.md
  docs/limitations.md
  docs/minimal/minimal.md
  docs/minimal/oracle.md
  docs/minimal/postgres.md
  docs/permissions.md
  docs/poc/oracle.md
  docs/poc/sqlserver.md
  docs/transformations/CustomTransformation.md
  docs/troubleshoot/faq.md
  docs/ui/connect-source.md
  docs/ui/prepare-migration/prepare.md
Labels: size/L
