Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2024-12, with the labels that each got.

#950 Add support for refreshing Spanner Client in VerifyExpressions API
  accessors/clients/spanner/client/interface.go
  accessors/clients/spanner/client/mocks.go
  accessors/clients/spanner/client/spanner_client.go
  accessors/spanner/spanner_accessor.go
  expressions_api/expression_verify.go
  expressions_api/expression_verify_test.go
Labels: size/M

#961 Using a claimed bucket code-base
  test_data/mysql_shard_streaming.cfg
Labels: size/XS

#962 Support check constraint backend
  common/constants/constants.go
  internal/convert.go
  internal/helpers.go
  internal/mapping.go
  internal/reports/report_helpers.go
  schema/schema.go
  sources/common/infoschema.go
  sources/common/toddl.go
  sources/common/toddl_test.go
  sources/dynamodb/schema.go
  sources/dynamodb/schema_test.go
  sources/mysql/infoschema.go
  sources/mysql/infoschema_test.go
  sources/mysql/mysqldump.go
  sources/oracle/infoschema.go
  sources/postgres/infoschema.go
  sources/spanner/infoschema.go
  sources/sqlserver/infoschema.go
  spanner/ddl/ast.go
  spanner/ddl/ast_test.go
  webv2/api/schema.go
  webv2/api/schema_test.go
  webv2/routes.go
  webv2/table/review_table_schema.go
  webv2/table/review_table_schema_test.go
  webv2/table/update_table_schema.go
Labels: size/XXL

#969 Updating version of msprod
  .github/workflows/integration-tests-against-emulator.yaml
Labels: size/S

#965 feat: APIs for Backend Changes for Default Values
  common/constants/constants.go
  conversion/conversion_from_source.go
  expressions_api/expression_verify.go
  expressions_api/expression_verify_test.go
  expressions_api/mocks.go
  internal/convert.go
  internal/helpers.go
  internal/reports/report_helpers.go
  schema/schema.go
  sources/common/infoschema.go
  sources/common/toddl.go
  sources/common/toddl_test.go
  sources/common/utils.go
  sources/common/utils_test.go
  spanner/ddl/ast.go
  spanner/ddl/ast_test.go
  webv2/api/schema.go
  webv2/table/utilities.go
Labels: size/XL

#970 feat: make spanner config mandatory for schema migration
  ui/cypress/e2e/spec.cy.ts
  ui/dist/ui/index.html
  ui/dist/ui/main.1cfa12bd9a851a7a.js
  ui/dist/ui/main.c082b8f8593afb56.js
  ui/src/app/components/direct-connection/direct-connection.component.spec.ts
  ui/src/app/components/direct-connection/direct-connection.component.ts
  ui/src/app/services/data/data.service.ts
  ui/src/app/services/fetch/fetch.service.ts
  webv2/config/config_handler.go
  webv2/routes.go
Labels: size/L

#945 Add Support for Check Constraint - Backend code changes
  common/constants/constants.go
  internal/convert.go
  internal/helpers.go
  internal/mapping.go
  internal/reports/report_helpers.go
  schema/schema.go
  sources/common/infoschema.go
  sources/common/toddl.go
  sources/common/toddl_test.go
  sources/dynamodb/schema.go
  sources/dynamodb/schema_test.go
  sources/mysql/infoschema.go
  sources/mysql/infoschema_test.go
  sources/mysql/mysqldump.go
  sources/oracle/infoschema.go
  sources/postgres/infoschema.go
  sources/spanner/infoschema.go
  sources/sqlserver/infoschema.go
  spanner/ddl/ast.go
  spanner/ddl/ast_test.go
  webv2/api/schema.go
  webv2/api/schema_test.go
  webv2/routes.go
  webv2/table/review_table_schema.go
  webv2/table/review_table_schema_test.go
  webv2/table/update_table_schema.go
Labels: size/XXL
