Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2024-03, with the labels that each got.

#780 added details about migration_shard_id rule
  docs/ui/schema-conv/sharded-migration.md
Labels: size/S

#778 feat: json resource generation cmd
  cmd/data.go
  cmd/schema_and_data.go
  cmd/utils.go
  conversion/conversion.go
  conversion/conversion_from_source.go
  conversion/conversion_from_source_test.go
  conversion/conversion_helper.go
  conversion/conversion_test.go
  conversion/conversion_types.go
  conversion/data_from_database.go
  conversion/get_info.go
  conversion/mocks.go
  conversion/resource_generation.go
  conversion/resource_generation_test.go
  conversion/snapshot_migration.go
  conversion/store_files.go
  conversion/validations.go
  go.mod
  go.sum
  internal/convert.go
  profiles/source_profile.go
  sources/common/infoschema.go
  sources/common/mocks.go
  sources/common/utils.go
  sources/common/utils_test.go
  streaming/streaming.go
  webv2/profile/profile.go
  webv2/web.go
Labels: size/XXL

#789 latest template and some documentation changes
  docs/reverse-replication/ReverseReplicationUserGuide.md
  docs/reverse-replication/RunnigReverseReplication.md
  reverse_replication/reverse-replication-runner.go
Labels: size/M

#803 Update the dataflow template path to latest released version
  streaming/streaming.go
Labels: size/XS
