Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2025-08, with the labels that each got.

#1169 fix for handling special characters in connection fields
  profiles/common.go
  profiles/common_test.go
  webv2/web.go
Labels: size/L

#1170 Fixing primary key sort order for source
  ui/src/app/components/object-detail/object-detail.component.ts
Labels: size/M

#1168 Adding performance schema collector for query assessments
  assessment/assessment_engine.go
  assessment/collectors/common/db_connector.go
  assessment/collectors/infoschema_collector.go
  assessment/collectors/performance_schema_collector.go
  assessment/collectors/performance_schema_collector_test.go
  assessment/sources/common.go
  assessment/sources/mysql/performance_schema.go
  assessment/sources/mysql/performance_schema_test.go
  assessment/utils/elements.go
Labels: size/XL

#1172 Fix assert order and statement
  testing/import_cmd/integration_test.go
Labels: size/XS

#1177 Added randomization to temp Db.
  expressions_api/expression_verify.go
Labels: size/S

#1187 added NUMERIC as an option as target datatype for BIGINT
  sources/mysql/toddl.go
  sources/mysql/toddl_test.go
Labels: size/XS

#1191 Update go mod and sum
  go.mod
  go.sum
Labels: size/XS

#1188 [Assessments] Making 'changes' a set to ensure unique values
  assessment/report_generator.go
Labels: size/S

#1193 Order output from map
  assessment/report_generator.go
  assessment/report_generator_test.go
Labels: size/S

#1194 Bigint unsigned handling
  internal/convert.go
  internal/reports/report_helpers.go
  sources/mysql/infoschema.go
  sources/mysql/infoschema_test.go
  sources/mysql/mysqldump.go
  sources/mysql/mysqldump_test.go
  sources/mysql/toddl.go
  sources/mysql/toddl_test.go
Labels: size/M
