Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2025-05, with the labels that each got.

#1112 Adding UTs to source schema parser and charset handling
  assessment/report_generator.go
  assessment/sources/mysql/infoschema.go
  assessment/sources/mysql/infoschema_test.go
  assessment/utils/assessment_output.go
Labels: size/XL

#1098 Upgrading angular cli and core to 18.2.17
  .github/workflows/integration-tests-against-emulator.yaml
  .github/workflows/lint.yaml
  .github/workflows/test-coverage.yaml
  ui/package-lock.json
  ui/package.json
  ui/src/app/app.module.ts
  ui/src/app/components/add-index-form/add-index-form.component.spec.ts
  ui/src/app/components/add-new-column/add-new-column.component.spec.ts
  ui/src/app/components/add-new-sequence/add-new-sequence.component.spec.ts
  ui/src/app/components/add-shard-id-primary-key/add-shard-id-primary-key.component.spec.ts
  ui/src/app/components/connection-profile-form/connection-profile-form.component.spec.ts
  ui/src/app/components/dataflow-form/dataflow-form.component.spec.ts
  ui/src/app/components/direct-connection/direct-connection.component.spec.ts
  ui/src/app/components/edit-column-max-length/edit-column-max-length.component.spec.ts
  ui/src/app/components/edit-global-datatype-form/edit-global-datatype-form.component.spec.ts
  ui/src/app/components/end-migration/end-migration.component.spec.ts
  ui/src/app/components/header/header.component.spec.ts
  ui/src/app/components/home/home.component.spec.ts
  ui/src/app/components/load-dump/load-dump.component.spec.ts
  ui/src/app/components/load-session/load-session.component.spec.ts
  ui/src/app/components/object-detail/object-detail.component.spec.ts
  ui/src/app/components/object-explorer/object-explorer.component.spec.ts
  ui/src/app/components/prepare-migration/prepare-migration.component.spec.ts
  ui/src/app/components/rule/rule.component.spec.ts
  ui/src/app/components/session-listing/session-listing.component.spec.ts
  ui/src/app/components/sharded-bulk-source-details-form/sharded-bulk-source-details-form.component.spec.ts
  ui/src/app/components/sharded-dataflow-migration-details-form/sharded-dataflow-migration-details-form.component.spec.ts
  ui/src/app/components/sidenav-review-changes/sidenav-review-changes.component.spec.ts
  ui/src/app/components/sidenav-rule/sidenav-rule.component.spec.ts
  ui/src/app/components/sidenav-save-session/sidenav-save-session.component.spec.ts
  ui/src/app/components/sidenav-view-assessment/sidenav-view-assessment.component.spec.ts
  ui/src/app/components/source-details-form/source-details-form.component.spec.ts
  ui/src/app/components/summary/summary.component.spec.ts
  ui/src/app/components/tune-datastream-form/tune-datastream-form.component.spec.ts
  ui/src/app/components/tune-gcs-form/tune-gcs-form.component.spec.ts
  ui/src/app/components/update-spanner-config-form/update-spanner-config-form.component.spec.ts
  ui/src/app/components/workspace/workspace.component.spec.ts
  ui/src/app/services/backend-health/backend-health.service.spec.ts
  ui/src/app/services/conversion/conversion.service.spec.ts
  ui/src/app/services/data/data.service.spec.ts
  ui/src/app/services/fetch/fetch.service.spec.ts
Labels: size/XL

#1089 feat(spanner): Add support for MYSQLDUMP in import command:
  accessors/spanner/mocks.go
  accessors/spanner/spanner_accessor.go
  cmd/import.go
  cmd/import_data_test.go
  cmd/import_test.go
  conversion/mocks.go
  expressions_api/expression_verify.go
  import_file/csv_data.go
  import_file/csv_data_test.go
  import_file/csv_schema.go
  import_file/csv_schema_test.go
  import_file/import_from_dump.go
  import_file/import_from_dump_test.go
  import_file/utils.go
  import_file/utils_test.go
  sources/common/dbdump.go
  sources/common/dbdump_test.go
  sources/common/mocks.go
  sources/common/toddl.go
  sources/mysql/mysqldump_test.go
  spanner/writer/batchwriter.go
  spanner/writer/batchwriter_test.go
  test_data/basic_mysql_dump.test.out
Labels: size/XXL

#1117 switching schema format from csv to json
  cmd/import.go
  cmd/import_test.go
  import_file/csv_data.go
  import_file/csv_data_test.go
  import_file/csv_schema.go
  import_file/csv_schema_test.go
  sources/common/infoschema.go
  sources/spanner/infoschema.go
  test_data/basic_csv_schema.csv
  test_data/basic_csv_schema.json
Labels: size/XL

#1016 feat: Interleave in and interleave in parent type
  accessors/spanner/spanner_accessor_test.go
  common/utils/utils.go
  docs/ui/schema-conv/spanner-draft.md
  sources/spanner/infoschema.go
  spanner/ddl/ast.go
  spanner/ddl/ast_test.go
  ui/src/app/components/object-detail/object-detail.component.html
  ui/src/app/components/object-detail/object-detail.component.ts
  ui/src/app/model/conv.ts
  ui/src/app/services/data/data.service.ts
  ui/src/app/services/fetch/fetch.service.ts
  ui/src/mocks/conv.ts
  webv2/api/schema.go
  webv2/api/schema_test.go
  webv2/primarykey/primarykey_service.go
  webv2/table/remove_column.go
  webv2/table/review_table_schema_test.go
  webv2/table/update_table_schema_test.go
Labels: size/L

#1108 chore(spanner): Add support for reading file from GCS.
  file_reader/file_reader.go
  file_reader/file_reader_test.go
  file_reader/gcs_file_reader.go
  file_reader/gcs_file_reader_test.go
  file_reader/local_file_reader.go
  file_reader/local_file_reader_test.go
  go.mod
  go.sum
  test_data/gcs_unit_test.replay
Labels: size/XXL

#1118 chore(spanner): Added integration test for import command using Mysql dump
  test_data/mysql_dump_import_data.sql
  testing/import_cmd/integration_test.go
Labels: size/L

#1120 chore(spanner): Minor refactoring:
  accessors/spanner/mocks.go
  accessors/spanner/spanner_accessor.go
  cmd/import.go
  cmd/import_test.go
  file_reader/file_reader_test.go
  file_reader/gcs_file_reader.go
  file_reader/gcs_file_reader_test.go
  file_reader/local_file_reader.go
  file_reader/local_file_reader_test.go
  import_file/csv_data.go
  import_file/csv_schema.go
  import_file/import_from_dump.go
  import_file/import_from_dump_test.go
  test_data/gcs_unit_test.replay
Labels: size/XL

#1122 Fix makefile to include npm install
  Makefile
Labels: size/XS

#1129 updated codecov version
  .github/workflows/test-coverage.yaml
Labels: size/XS

#1130 Import: Handling missing case for table name defaults
  cmd/import.go
  cmd/import_test.go
  import_file/csv_schema.go
Labels: size/S

#1121 chore(spanner): Added mysql example data sets to Import command integration tests.
  test_data/menagerie.sql
  test_data/sakila-dump.sql
  test_data/world.sql
  testing/import_cmd/integration_test.go
Labels: size/XXL
