Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2025-06, with the labels that each got.

#1140 minor fixes in assessments
  assessment/collectors/app_code_collector.go
  assessment/report_generator.go
Labels: size/S

#1126 feat: Adding Vertx Framework support in App Code Assessments
  assessment/collectors/app_code_collector.go
  assessment/collectors/embeddings/generate_embedding.go
  assessment/collectors/embeddings/vector_search.go
  assessment/collectors/embeddings/vertx_concept_examples.json
  assessment/collectors/project_analyzer/file_dependency_analyzer.go
Labels: size/M

#1128 test: Unit Tests for App Code assessment
  assessment/collectors/app_code_collector.go
  assessment/collectors/app_code_collector_test.go
  assessment/collectors/embeddings/generate_embedding.go
  assessment/collectors/embeddings/generate_embedding_test.go
  assessment/collectors/embeddings/vector_search.go
  assessment/collectors/embeddings/vector_search_test.go
  assessment/collectors/parser/response_parser.go
  assessment/collectors/parser/response_parser_test.go
  assessment/collectors/project_analyzer/file_dependency_analyzer.go
  assessment/collectors/project_analyzer/file_dependency_analzyer_test.go
  assessment/collectors/project_analyzer/java_file_dependency_analyzer.go
  assessment/collectors/project_analyzer/java_file_dependency_analyzer_test.go
Labels: size/XXL

#1145 Add locks to avoid race condition during schema discovery
  sources/mysql/infoschema.go
Labels: size/XS
