Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2025-04, with the labels that each got.

#1068 Data import: Basic functionality. Works with existing schema
  accessors/clients/spanner/client/interface.go
  accessors/clients/spanner/client/mocks.go
  accessors/spanner/mocks.go
  accessors/spanner/spanner_accessor.go
  cmd/import_data.go
  cmd/import_data_test.go
  common/utils/utils.go
  import_data/csv_data.go
  import_data/csv_data_test.go
  import_data/csv_schema.go
  import_data/csv_schema_test.go
  sources/csv/data.go
  sources/csv/data_test.go
  sources/spanner/infoschema.go
  test_data/basic_csv_schema.csv
Labels: size/XXL

#1074 Adjust code Codecov
  .github/codecov.yml
Labels: size/XS

#1076 Updating go `net` and `resource-manager`
  go.mod
  go.sum
Labels: size/L

#1077 Fixing issues in dependencies pr #1057 to update dataflow version.
  go.mod
  go.sum
Labels: size/XS

#1079 Update Renovate on Wednesdays.
  renovate.json
Labels: size/XS

#1075 Adding package.lock to pin dependencies. Also add a Workflow for checking package.lock
  .github/workflows/check-package-lock.yaml
  .gitignore
  ui/package-lock.json
Labels: size/M

#1082 Add integration with open source client
  sources/cassandra/Dockerfile
  sources/cassandra/entrypoint.sh
  sources/cassandra/variables.tf
Labels: size/S

#1078 feat: Adding support for JDBC Projects in Application Code Assessment
  assessment/collectors/app_migration_analysis.go
  assessment/collectors/embeddings/generate_embedding.go
  assessment/collectors/embeddings/go_concept_examples.json
  assessment/collectors/embeddings/java_concept_examples.json
  assessment/collectors/embeddings/vector_search.go
  assessment/collectors/prompts/analyze-code-prompt.txt
  assessment/collectors/prompts/dao-migration-prompt.txt
  assessment/collectors/prompts/non-dao-migration-prompt.txt
Labels: size/XL

#1081 Phase-2 of adding package-lock.json
  .github/workflows/check-package-lock.yaml
  .gitignore
  Makefile
Labels: size/S

#1088 Point validation script to use spanner directly
  go.mod
  go.sum
  sources/cassandra/validations/validation/validation.go
Labels: size/L

#1090 Updated pg query version due to latest mac changes
  go.mod
  go.sum
  sources/postgres/pgdump.go
  sources/postgres/pgdump_test.go
Labels: size/XS

#1096 Upgrading angular material and cdk to 17
  ui/package-lock.json
  ui/package.json
Labels: size/XS

#1091 refactor: Refactor the app assessment code to use proper naming conventions
  assessment/assessment_engine.go
  assessment/collectors/app_migration_analysis.go
  assessment/collectors/prompts/dao-migration-prompt.txt
  assessment/collectors/prompts/non-dao-migration-prompt.txt
  assessment/eval_test.go
Labels: size/XL

#1106 updating live migration metrics in the docs
  docs/troubleshoot/minimal.md
Labels: size/M

#1099 refactor: Making the collectors concurrent
  assessment/assessment_engine.go
  assessment/collectors/app_code_collector.go
  assessment/collectors/project_analyzer/file_dependency_analyzer.go
  assessment/collectors/project_analyzer/java_file_dependency_analyzer.go
  assessment/eval_test.go
  assessment/utils/assessment_output.go
Labels: size/L

#977 docs: reverse replication docs update
  docs/reverse-replication/ReverseReplicationUserGuide.md
  docs/reverse-replication/RunnigReverseReplication.md
Labels: size/XL
