Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2025-07, with the labels that each got.

#1152 Updating build from source instructions
  docs/install.md
Labels: size/XS

#1153 Added fix for creating database in PG Dialect via import command.
  accessors/spanner/spanner_accessor.go
  accessors/spanner/spanner_accessor_test.go
Labels: size/M

#1156 Bug fixes in UI support of Cassandra Schema Migration
  ui/src/app/app.constants.ts
  ui/src/app/components/load-session/load-session.component.ts
  ui/src/app/components/object-detail/object-detail.component.html
  ui/src/app/services/conversion/conversion.service.spec.ts
  ui/src/app/services/conversion/conversion.service.ts
Labels: size/M

#1155 Added Function testing for PG DUMP in Import command
  test_data/pagila.sql
  test_data/pg_world.sql
  testing/import_cmd/integration_test.go
Labels: size/XXL

#1157 Enhance Error Reporting for Cassandra source and Fix Singleton Cluster Configuration Issue
  accessors/clients/cassandra/cassandra_client.go
  accessors/clients/cassandra/cassandra_client_test.go
  internal/convert.go
  internal/reports/report_helpers.go
  sources/cassandra/toddl.go
  sources/cassandra/toddl_test.go
Labels: size/L

#1158 minor doc updates
  docs/transformations/CustomTransformation.md
Labels: size/S

#1159 Increases per operation mutation count to 80k
  spanner/writer/batchwriter.go
Labels: size/XS

#1151 Support schema migration for non empty ddl on spanner
  accessors/spanner/mocks.go
  accessors/spanner/spanner_accessor.go
  accessors/spanner/spanner_accessor_test.go
  cmd/utils.go
  import_file/import_from_dump_test.go
  testing/conversion/conversion_test.go
Labels: size/L

#1160 minor fixes to documentation
  docs/transformations/CustomTransformation.md
Labels: size/XS

#1148 feat: Adding support for Hibernate framework
  assessment/collectors/app_code_collector.go
  assessment/collectors/embeddings/generate_embedding.go
  assessment/collectors/embeddings/hibernate_concept_examples.json
Labels: size/L

#1139 Functional tests for CSV format on import command
  cmd/import.go
  cmd/import_test.go
  import_file/csv_schema.go
  import_file/csv_schema_test.go
  testing/import_cmd/integration_test.go
  testing/import_data/integration_test.go
Labels: size/L

#1165 Upgrade Go to 1.24 in Dockerfile
  sources/cassandra/Dockerfile
Labels: size/XS

#1161 Documentation for Cassandra Schema Migration
  docs/cli/flags.md
  docs/data-types/cassandra.md
  docs/data-types/schema.md
  docs/index.md
Labels: size/L

#1166 Fixing binary schema migration for mysql to map to correct spanner type with length BYTES(XX)
  sources/mysql/mysqldump_test.go
  sources/mysql/toddl.go
  sources/mysql/toddl_test.go
Labels: size/S
