Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2025-01, with the labels that each got.

#978 verification API and dump flow changes to support MySQL CHECK CONSTRAINTS
  common/utils/utils.go
  conversion/conversion.go
  conversion/conversion_from_source.go
  conversion/conversion_helper.go
  expressions_api/expression_verify.go
  internal/convert.go
  internal/reports/report_helpers.go
  mocks/expressions_api_mock.go
  schema/schema.go
  sources/common/dbdump.go
  sources/common/toddl.go
  sources/common/toddl_test.go
  sources/dynamodb/schema_test.go
  sources/dynamodb/toddl_test.go
  sources/mysql/infoschema.go
  sources/mysql/infoschema_test.go
  sources/mysql/mysqldump.go
  sources/mysql/mysqldump_test.go
  sources/mysql/report_test.go
  sources/mysql/toddl_test.go
  sources/oracle/infoschema_test.go
  sources/oracle/toddl_test.go
  sources/postgres/infoschema_test.go
  sources/postgres/pgdump.go
  sources/postgres/pgdump_test.go
  sources/postgres/report_test.go
  sources/postgres/toddl_test.go
  sources/sqlserver/infoschema_test.go
  sources/sqlserver/toddl_test.go
  spanner/ddl/ast.go
  testing/csv/integration_test.go
  testing/dynamodb/snapshot/integration_test.go
  testing/dynamodb/streaming/integration_test.go
  testing/mysql/integration_test.go
  testing/oracle/integration_test.go
  testing/postgres/golden_test.go
  testing/postgres/integration_test.go
  testing/sqlserver/integration_test.go
  webv2/api/schema.go
  webv2/api/schema_test.go
  webv2/routes.go
Labels: size/XXL

#984 Replace ReadOnlyTransaction() with Single()
  accessors/clients/spanner/client/interface.go
Labels: size/XS

#980 Documentation for check constraints
  docs/data-types/mysql.md
  docs/limitations.md
  docs/troubleshoot/faq.md
  docs/ui/schema-conv/issues.md
  docs/ui/schema-conv/schema-conv.md
  docs/ui/schema-conv/spanner-draft.md
Labels: size/M

#922 minor docs cleanup
  docs/quickstart.md
Labels: size/XS

#983 Integration test checkconstraints
  .github/workflows/integration-tests-against-emulator.yaml
  conversion/conversion_from_source.go
  sources/common/toddl.go
  sources/mysql/infoschema.go
  sources/mysql/mysqldump.go
  test_data/mysql_checkconstraint_dump.test.out
  test_data/test_session_mysql_test_smt.json
  testing/mysql/integration_test.go
  ui/src/app/components/workspace/workspace.component.ts
  webv2/api/schema.go
Labels: size/XXL

#988 fix: add new PK before verification API is called
  sources/common/dbdump.go
  sources/common/infoschema.go
  sources/common/toddl.go
  sources/dynamodb/toddl_test.go
  sources/mysql/toddl_test.go
  sources/oracle/toddl_test.go
  sources/postgres/toddl_test.go
  sources/sqlserver/toddl_test.go
  testing/postgres/golden_test.go
Labels: size/M

#987 updated the Build of UI
  ui/dist/ui/index.html
Labels: size/XS
