Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2025-02, with the labels that each got.

#995 feat: parenthesis on the check constraints expressions.
  webv2/api/schema.go
  webv2/api/schema_test.go
Labels: size/M

#998 Updating installation instructions and required versions in the doc pages
  docs/install.md
Labels: size/S

#999 bugfix - Check Constraint PG Dialect
  internal/reports/report_helpers.go
  sources/common/toddl.go
  spanner/ddl/ast.go
  spanner/ddl/ast_test.go
Labels: size/L

#1000 fix: Spanner Client refresh fix
  mocks/expressions_api_mock.go
  sources/common/toddl.go
  sources/common/toddl_test.go
  spanner/ddl/ast.go
Labels: size/M

#1003 fix: Query modification and Refresh Client Issue
  sources/common/dbdump.go
  sources/common/infoschema.go
  sources/mysql/infoschema.go
  sources/mysql/infoschema_test.go
  webv2/api/schema.go
  webv2/api/schema_test.go
Labels: size/S

#1005 Fix: Error Handling for CLI flow using Session file
  cmd/schema.go
Labels: size/XS

#1010 Adding go.sum towards 3.5.0 release
  go.sum
Labels: size/S

#1011 Use `spanner_migration_tool_output/config` as config file path
  webv2/config/config_service.go
Labels: size/M

#1021 upgrade go version to 1.22.7
  .github/workflows/integration-tests-against-emulator.yaml
  .github/workflows/lint.yaml
  .github/workflows/test-coverage.yaml
  docs/install.md
  go.mod
  go.sum
Labels: size/S

#1025 Refactoring tests for CLI cmds
  cmd/data_test.go
  cmd/schema_and_data_test.go
Labels: size/L

#1027 Add comprehensive testing to CLI cmds
  cmd/data_test.go
  cmd/schema_and_data_test.go
Labels: size/L
