Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2025-09, with the labels that each got.

#1200 Capping size for (`""`|`"medium"`|`"tiny"`|`"long"`)Blob to BYTES mappings reflect mySql Storage limits.
  docs/data-types/mysql.md
  sources/mysql/mysqldump_test.go
  sources/mysql/toddl.go
  sources/mysql/toddl_test.go
Labels: size/L

#1202 Bigint Unsigned to numeric mysql dropdown issue PR
  sources/mysql/toddl.go
  webv2/api/schema.go
Labels: size/XS

#1209 Added more mysql to spanner query translation samples
  assessment/utils/mysql_query_examples.json
Labels: size/XL
