Repository GoogleCloudPlatform/spanner-migration-tool, pull requests merged in 2025-03, with the labels that each got.

#1033 feat(spanner): Adding frameworks needed for Source Code Assessment
  assessment/collectors/app_migration_analysis.go
  assessment/collectors/embeddings/concept_examples.json
  assessment/collectors/embeddings/generate_embedding.go
  assessment/collectors/embeddings/vector_search.go
  assessment/collectors/parser/response_parser.go
  assessment/collectors/project_analyzer/file_dependency_analyzer.go
  assessment/utils/elements.go
  go.mod
  go.sum
Labels: size/XXL

#1019 fix: back tick foreign key column name
  spanner/ddl/ast.go
  spanner/ddl/ast_test.go
  webv2/api/sequence.go
Labels: size/L

#1035 adding spanner schema assessment information
  assessment/assessment_engine.go
  assessment/collectors/infoschema_collector.go
  assessment/report_generator.go
  assessment/sources/common.go
  assessment/sources/mysql/infoschema.go
  assessment/utils/assessment_output.go
  assessment/utils/elements.go
  internal/helpers.go
Labels: size/L

#1037 fix: disable parallel test for check constraints
  testing/mysql/integration_test.go
Labels: size/XS

#1038 added db impact implementation
  assessment/report_generator.go
  assessment/utils/assessment_output.go
Labels: size/L

#1036 feat(spanner): Extend App Assessment to analyse entire Go project
  assessment/collectors/app_migration_analysis.go
  assessment/collectors/embeddings/generate_embedding.go
  assessment/collectors/embeddings/vector_search.go
  assessment/collectors/project_analyzer/file_dependency_analyzer.go
  go.mod
  go.sum
Labels: size/L

#1039 fix(spanner): View assessment does not show detailed report and the download report functionality was not working
  ui/src/app/components/sidenav-view-assessment/sidenav-view-assessment.component.ts
  webv2/routes.go
Labels: size/S

#1040 Fetch unsigned column attribute for infoschema assessment
  assessment/collectors/infoschema_collector.go
  assessment/sources/common.go
  assessment/sources/mysql/infoschema.go
  assessment/utils/assessment_output.go
  assessment/utils/elements.go
Labels: size/M

#1043 generate mysql ddl from conv - SrcSchema
  assessment/mysql_ddl.go
  sources/mysql/infoschema.go
Labels: size/L

#1042 fix(spanner): Fixed parsing of Snippets
  assessment/collectors/app_migration_analysis.go
  assessment/collectors/parser/response_parser.go
Labels: size/M

#1044 app assessment integration initial commit
  assessment/assessment_engine.go
  assessment/collectors/app_migration_analysis.go
  assessment/collectors/project_analyzer/file_dependency_analyzer.go
  assessment/report_generator.go
  assessment/utils/assessment_output.go
  assessment/utils/elements.go
  assessment/utils/files.go
  cmd/assessment.go
Labels: size/L

#1030 Unit Tests: Wide Row
  accessors/spanner/spanner_accessor_test.go
Labels: size/L

#1048 Git ignore ui/dist and package-lock.json
  .github/scripts/verify-files.sh
  .github/workflows/integration-tests-against-emulator.yaml
  .github/workflows/lint.yaml
  .github/workflows/test-coverage.yaml
  .github/workflows/ui-generated-files-check.yaml
  .gitignore
  Makefile
  ui/dist/ui/3rdpartylicenses.txt
  ui/dist/ui/assets/gifs/database-loader.gif
  ui/dist/ui/assets/icons/google-spanner-logo.png
  ui/dist/ui/favicon.ico
  ui/dist/ui/index.html
  ui/dist/ui/main.ba053e44d0c0e200.js
  ui/dist/ui/polyfills.c2c201edf5092294.js
  ui/dist/ui/runtime.30e542cf552662e5.js
  ui/dist/ui/styles.9b18c896a09ee20d.css
  ui/package-lock.json
Labels: size/XXL

#1051 moved calculation logic to assessment engine
  assessment/assessment_engine.go
  assessment/collectors/infoschema_collector.go
  assessment/collectors/sample_collector.go
  assessment/report_generator.go
  assessment/sources/common.go
  assessment/sources/mysql/infoschema.go
  assessment/utils/assessment_output.go
  assessment/utils/elements.go
Labels: size/XL

#1050 [DRAFT] Initial commit for data import interface
  cmd/import_data.go
  cmd/import_data_test.go
  main.go
  test_data/basic_csv.csv
  test_data/basic_csv_schema.csv
  test_data/import_data_integ_test_csv.json
  testing/import_data/integration_test.go
Labels: size/L

#1059 Update docs for FKA
  docs/data-types/mysql.md
  docs/data-types/postgres.md
  docs/limitations.md
Labels: size/XS

#1055 feat(spanner): Use mysql schema from conv object for App assessment
  assessment/assessment_engine.go
  assessment/collectors/app_migration_analysis.go
  assessment/collectors/parser/response_parser.go
  assessment/collectors/project_analyzer/file_dependency_analyzer.go
Labels: size/L

#1061 feat(spanner): Updated Gemini prompts and Parallel processing of files
  assessment/collectors/app_migration_analysis.go
  assessment/collectors/project_analyzer/file_dependency_analyzer.go
Labels: size/L

#1060 Update WaitGroup handling
  common/task/task.go
Labels: size/S

#1058 Add support for views, charset and other schema features
  assessment/assessment_engine.go
  assessment/collectors/infoschema_collector.go
  assessment/report_generator.go
  assessment/sources/common.go
  assessment/sources/mysql/infoschema.go
  assessment/utils/assessment_output.go
  assessment/utils/elements.go
  assessment/utils/mysql_ddl.go
  internal/helpers.go
  internal/mapping.go
  internal/mapping_test.go
Labels: size/XXL

#1062 feat(spanner): Added report generation for non schema changes and increase buffer size for scanning code files.
  assessment/collectors/app_migration_analysis.go
  assessment/report_generator.go
  assessment/utils/files.go
Labels: size/L

#1063 Assessment report update
  assessment/assessment_engine.go
  assessment/collectors/app_migration_analysis.go
  assessment/collectors/parser/response_parser.go
  assessment/collectors/project_analyzer/file_dependency_analyzer.go
  assessment/report_generator.go
  assessment/utils/elements.go
  cmd/assessment.go
  sources/common/infoschema.go
Labels: size/L

#1052 Add dockerfile and terraform scripts
  sources/cassandra/Dockerfile
  sources/cassandra/entrypoint.sh
  sources/cassandra/main.tf
  sources/cassandra/outputs.tf
  sources/cassandra/sample-zdm-config.yaml
  sources/cassandra/terraform.tf
  sources/cassandra/terraform.tfvars
  sources/cassandra/variables.tf
Labels: size/L

#1067 feat: Adding Evaluation Utility to Check Accuracy for Assessment
  assessment/collectors/app_migration_analysis.go
  assessment/eval_data.json
  assessment/eval_test.go
Labels: size/L

#1069 feat(spanner): Implement file dependency analyzer for Java code:
  assessment/assessment_engine.go
  assessment/collectors/app_migration_analysis.go
  assessment/collectors/project_analyzer/file_dependency_analyzer.go
  assessment/collectors/project_analyzer/java_file_dependency_analyzer.go
  assessment/eval_test.go
  go.mod
  go.sum
Labels: size/L

#1064 moved snippets into app code assessment and corrected default null ha…
  assessment/assessment_engine.go
  assessment/collectors/app_migration_analysis.go
  assessment/collectors/parser/response_parser.go
  assessment/report_generator.go
  assessment/utils/assessment_output.go
  assessment/utils/elements.go
  assessment/utils/report_utils.go
Labels: size/L

#1070 Validation scripts for cassandra live
  go.mod
  go.sum
  sources/cassandra/README.md
  sources/cassandra/validations/count/count.go
  sources/cassandra/validations/validation/validation.go
Labels: size/XXL
